### ISSUE TITLE
Tag support in JavaScript agent

### ISSUE THREAD

**Issue by vatima2016** [instana/weasel#3]
Java script agent should support tags to ensure consistent view on the application map

**Comment by bripkens** [comment]
Hello @vatima2016,

we just extended the metadata support for exactly this purpose. In the next Instana release, you will be able to use the metadata as part of the Instana service extraction to structure your application map.

Meaning: Services can be defined using the configured application name and your defined metadata fields. This means that you can use meta data fields as key/value based tags.

I'll close this ticket for now as weasel has support for tagging via metadata. If you have further questions, feel free to open an [Instana support ticket](support.instana.com/hc).

Cheers,

Ben
