### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by buildscientist** [instana/weasel#8]
Is there any documentation on using this library? I'm trying to do a comparison between Weasel and Boomerang. Thanks.

**Comment by bripkens** [comment]
Hi @buildscientist,

we were lacking basic usage docs, but I added some just now:

https://github.com/instana/weasel#usage

Hope this helps you.

Cheers,

/ben

**Comment by buildscientist** [comment]
@bripkens Thanks - this is very helpful.
